### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by jersobh** [StreamMachine/StreamMachine#100]
17405/sourcein -- debug: Incoming source attempt.
/home/jeff/Projetos/radio2/server/js/src/streammachine/master/source_in.js:242
        return this.info.headers[match[1].toLowerCase()] = match[2];
                                      ^

TypeError: Cannot read property '1' of null
    at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.HEADER (/home/jeff/Projetos/radio2/server/js/src/streammachine/master/source_in.js:242:39)
    at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.execute (/home/jeff/Projetos/radio2/server/js/src/streammachine/master/source_in.js:175:25)
    at Socket.<anonymous> (/home/jeff/Projetos/radio2/server/js/src/streammachine/master/source_in.js:62:32)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:502:10)
    at emitReadable (_stream_readable.js:496:7)
    at addChunk (_stream_readable.js:263:7)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)

**Comment by nakedsushi** [comment]
@jersobh are you using icecast as an input source? What do your headers look like?

**Comment by jersobh** [comment]
Nope, VLC. I'll try again at home later and then I'll post the results here. Thanks!
