### ISSUE TITLE
Crash when using Redis on fresh install ("TypeError: Cannot call method 'substr' of null")

### ISSUE THREAD

**Issue by sjourdan** [StreamMachine/StreamMachine#43]
Hi,

I'm trying to use this simple configuration to add Redis support in the standalone mode (I'm on the master branch):

```
"redis": {
        "server": "redis://localhost:6379"
}
```
And I'm getting the following trace: 

```
root@vagrant:/srv/StreamMachine# ./streammachine-cmd --config ./config/standalone-redis.json
adding Console transport
4421 -- debug: StreamMachine standalone initialized.
4421 -- debug: Attaching listener for SIGUSR2 restarts.
4421/master -- debug: Initializing Redis connection
init redis with  redis://localhost:6379
4421/master -- debug: Registering config_update listener
4421 -- info: Attaching listeners.
4421 -- debug: Standalone is listening on port 8001

/srv/StreamMachine/node_modules/redis/index.js:535
            throw err;
                  ^
TypeError: Cannot call method 'substr' of null
  at RedisClient.<anonymous> (/srv/StreamMachine/src/streammachine/redis.coffee:27:45)
  at RedisClient.g (events.js:180:16)
  at RedisClient.EventEmitter.emit (events.js:92:17)
  at RedisClient.on_ready (/srv/StreamMachine/node_modules/redis/index.js:318:10)
  at RedisClient.on_info_cmd (/srv/StreamMachine/node_modules/redis/index.js:349:14)
  at /srv/StreamMachine/node_modules/redis/index.js:373:14
  at try_callback (/srv/StreamMachine/node_modules/redis/index.js:532:9)
  at RedisClient.return_reply (/srv/StreamMachine/node_modules/redis/index.js:614:13)
  at ReplyParser.<anonymous> (/srv/StreamMachine/node_modules/redis/index.js:266:14)
  at ReplyParser.EventEmitter.emit (events.js:95:17)
  at ReplyParser.send_reply (/srv/StreamMachine/node_modules/redis/lib/parser/javascript.js:300:10)
  at ReplyParser.execute (/srv/StreamMachine/node_modules/redis/lib/parser/javascript.js:203:22)
  at RedisClient.on_data (/srv/StreamMachine/node_modules/redis/index.js:488:27)
  at Socket.<anonymous> (/srv/StreamMachine/node_modules/redis/index.js:82:14)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

Steps to reproduce: 

* boot the chef/ubuntu-14.04 vagrant box

```
apt-get update
apt-get upgrade
apt-get install nodejs npm git nodejs-legacy software-properties-common
mkdir /var/log/streammachine
cd /srv
git clone https://github.com/StreamMachine/StreamMachine.git
# git branch
* master
cd StreamMachine
npm install
./streammachine-cmd --config ./config/standalone.json
```
=> this works perfectly well, get on the redis part:

```
# add the redis repo
add-apt-repository ppa:chris-lea/redis-server
apt-get install redis-server
# verify redis answers 
redis-cli ping
PONG
cp config/standalone.json config/standalone-redis.json
# insert the above configuration
./streammachine-cmd --config ./config/standalone-redis.json
[...]
TypeError: Cannot call method 'substr' of null
[...]
```

Thank you for your work and how can I help you on this issue ?

**Comment by ewr** [comment]
Thanks @sjourdan! We were incorrectly handling Redis specs that didn't include a database number. Should be fixed now.
