### ISSUE TITLE
localhost:8001/api returns "Invalid Stream"

### ISSUE THREAD

**Issue by pedropapa** [StreamMachine/StreamMachine#47]
Hello,
I'm trying to get data from the StreamMachine API, but it always returns the message "Invalid Stream". Maybe there is some configuration missing?

I'm just using the tutorial configuration, with 8002 source port, "test" as key and "testing" as password, I'm able to stream the music and listen to it at localhost:8001, everything works fine, but when I try to access the api at localhost:8001/api it always returns "Invalid Stream".

My config:
```
{
	"port":			    8001,
	"source_port":	8002,
	"log": {
		"stdout":     true
  },
  "streams": {
    "test": {
      "key":              "test",
      "root_route":       true,
      "format":           "mp3",
      "seconds":          3600,
      "metaTitle":        "Testing",
      "host":             "localhost",
      "source_password":  "testing"
    }
  }
}
```

**Comment by ewr** [comment]
In Standalone mode, the API and the streams get mounted on the same server. If a route doesn't match on the API, it falls through to the stream handler, which tells us that API isn't a valid stream.

So, not a useful message, but not technically incorrect.

You'll want to try specific endpoints for the API, such as `/api/streams`. You can pretty easily figure out what endpoints are supported by looking at the code here:

https://github.com/StreamMachine/StreamMachine/blob/master/src/streammachine/master/admin/api.coffee#L58-L189

**Comment by pedropapa** [comment]
Thank you, I'm able to see the API output now, but some of the endpoints seems to be not working.

/api/stream/:stream - What stream parameter refers to? stream id? I tried using "id", "key" and "streamkey" variables got from /api/streams, but none of them worked, I just receive the message "Cannot GET /api/stream/test". The /api/streams returns the following json object:
```
[
  {
    "key": "test",
    "id": "test",
    "vitals": {
      "streamKey": "mp3-32000-96-s",
      "framesPerSec": 27.77777777777778,
      "emitDuration": 2
    },
    "sources": [
      {
        "source": "Icecast (201.18.150.191:63080)",
        "connected": true,
        "url": "201.18.150.191:63080",
        "streamKey": "mp3-32000-96-s",
        "uuid": "356e8561-9bc6-4ee6-b3eb-c0b265fa731a",
        "last_ts": "2015-08-15T23:58:30.287Z",
        "connected_at": "2015-08-15T23:23:41.710Z"
      }
    ],
    "rewind": {
      "buffer_length": 1800,
      "first_buffer_ts": "2015-08-15T22:53:23.632Z",
      "last_buffer_ts": "2015-08-15T23:58:30.287Z",
      "hls_segments": 362,
      "hls_first_seg_id": 979,
      "hls_first_seg_ts": "2015-08-15T22:53:30.000Z",
      "hls_last_seg_id": 1340,
      "hls_last_seg_ts": "2015-08-15T23:58:20.000Z"
    }
  }
]
```
/api/listeners - just keep loading until browser times out the connection.
/api/users - Throws the following exception:
```
TypeError: Object.keys called on non-object
  at Function.keys (native)
  at Local._user_list (/home/brazucas/StreamMachine/src/streammachine/master/admin/users.coffee:82:38)
  at Local.module.exports.Users.list (/home/brazucas/StreamMachine/src/streammachine/master/admin/users.coffee:15:10)
  at /home/brazucas/StreamMachine/src/streammachine/master/admin/api.coffee:165:20
  at callbacks (/home/brazucas/StreamMachine/node_modules/express/lib/router/index.js:164:37)
  at param (/home/brazucas/StreamMachine/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/brazucas/StreamMachine/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/home/brazucas/StreamMachine/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/home/brazucas/StreamMachine/node_modules/express/lib/router/index.js:33:10)
  at next (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.handle (/home/brazucas/StreamMachine/src/streammachine/master/admin/api.coffee:49:13)
  at next (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.expressInit [as handle] (/home/brazucas/StreamMachine/node_modules/express/lib/middleware.js:30:5)
  at next (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.query [as handle] (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
  at next (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Function.app.handle (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:198:3)
  at Object.fn [as handle] (/home/brazucas/StreamMachine/node_modules/express/lib/application.js:120:11)
  at next (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.expressInit [as handle] (/home/brazucas/StreamMachine/node_modules/express/lib/middleware.js:30:5)
  at next (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Object.query [as handle] (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
  at next (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at Function.app.handle (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/proto.js:198:3)
  at Server.app (/home/brazucas/StreamMachine/node_modules/express/node_modules/connect/lib/connect.js:65:37)
  at Server.EventEmitter.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2108:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socket.ondata (http.js:1966:22)
  at TCP.onread (net.js:527:27)
```

**Comment by ewr** [comment]
I think the main problem here is that the default config leaves users in a state where not all functions are available, and the documentation doesn't do a good job explaining that. 

The stream endpoints are at `/api/streams/:stream`, not `/api/stream/:stream`. `:stream` is the `key` in your config.

The `/api/listeners` endpoint requires that analytics be configured and that StreamMachine have a connection to Elasticsearch, but it doesn't properly warn you if that's not the case. That's a bug. You can see the [analytics configuration section in the wiki](https://github.com/StreamMachine/StreamMachine/wiki/Configuration-settings#analytics) for info on what you would need to set to enable analytics (basically just `analytics:es_uri`).

`/api/users` expects that if you aren't storing configuration to Redis, you're going to have a dictionary of users defined in your config. The current code doesn't properly handle the case where you are using Redis, don't have any users in the config, but still want a list.
