### ISSUE TITLE
"Error: Buffer.write(string, encoding, offset[, length]) is no longer supported" when creating a new stream using the API

### ISSUE THREAD

**Issue by dvlprs** [StreamMachine/StreamMachine#93]
Hi,

Trying the [Installation-for-Ubuntu#use-redis-backend-with-streammachine](https://github.com/StreamMachine/StreamMachine/wiki/Installation-for-Ubuntu#use-redis-backend-with-streammachine) tutorial.
```
>curl -F 'key=teststream' http://a.b.c.d:8001/api/streams
Error: Buffer.write(string, encoding, offset[, length]) is no longer supported
    at Buffer.write (buffer.js:739:11)
    at MultipartParser.initWithBoundary (/srv/StreamMachine/node_modules/formidable/lib/multipart_parser.js:61:17)
    at IncomingForm._initMultipart (/srv/StreamMachine/node_modules/formidable/lib/incoming_form.js:308:10)
    at IncomingForm._parseContentType (/srv/StreamMachine/node_modules/formidable/lib/incoming_form.js:250:12)
    at IncomingForm.writeHeaders (/srv/StreamMachine/node_modules/formidable/lib/incoming_form.js:129:8)
    at IncomingForm.parse (/srv/StreamMachine/node_modules/formidable/lib/incoming_form.js:97:8)
    at /srv/StreamMachine/node_modules/connect/lib/middleware/multipart.js:126:12
    at noop (/srv/StreamMachine/node_modules/connect/lib/middleware/multipart.js:22:3)
    at multipart (/srv/StreamMachine/node_modules/connect/lib/middleware/multipart.js:76:5)
    at /srv/StreamMachine/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at urlencoded (/srv/StreamMachine/node_modules/connect/lib/middleware/urlencoded.js:54:72)
    at /srv/StreamMachine/node_modules/connect/lib/middleware/bodyParser.js:55:7
    at json (/srv/StreamMachine/node_modules/connect/lib/middleware/json.js:56:55)
    at bodyParser (/srv/StreamMachine/node_modules/connect/lib/middleware/bodyParser.js:53:5)
    at callbacks (/srv/StreamMachine/node_modules/express/lib/router/index.js:164:37)
    at param (/srv/StreamMachine/node_modules/express/lib/router/index.js:138:11)
```

```
# node -v
v6.5.0
```

**Comment by dvlprs** [comment]
https://github.com/felixge/node-formidable/issues/364
